var constants = require('./constants'),
	organisations = require('./modules/organisations'),
	users = require('./modules/users'),
	venues = require('./modules/venues'),
	events = require('./modules/events'),
	auth = require('./modules/auth');
	products = require('./modules/products'),
	promoters = require('./modules/promoters'),
	tableTypes = require('./modules/table-types'),
	replies = require('./modules/replies'),
	queries = require('./modules/queries'),
	orders = require('./modules/orders');

module.exports.organisations = organisations;
module.exports.venues = venues;
module.exports.events = events;
module.exports.auth = auth;
module.exports.users = users;
module.exports.products = products;
module.exports.promoters = promoters;
module.exports.tableTypes = tableTypes;
module.exports.replies = replies;
module.exports.queries = queries;
module.exports.orders = orders;